data_path: '/home/zhz/dataset/places365_standard'
log_dir: logs
weight_dir: checkpoints
arch: mobilenet_v2
workers: 6
epochs: 90
start_epoch: 0
batch_size: 256
lr: 0.1
momentum: 0.9
weight_decay: 1e-4
print_freq: 10
resume: False
evaluate: False
pretrained: False
num_classes: 365
dataset: places365